### ISSUE TITLE
Initial version done and deployed

### ISSUE THREAD

**Issue by ayan-biswas0412** [djm-1/dibyajyotimondal#2]
have a look https://juetcefreshers.github.io/opensource-portfolio/
Thank you @djm-1 for helping me in the design aspects I have copied some of your CSS and rewritten them in react have a look at the repository also https://github.com/juetcefreshers/opensource-portfolio

See the readme I have written some instructions for the people who want to add projects https://github.com/juetcefreshers/opensource-portfolio/blob/main/README.md

**Comment by djm-1** [comment]
@ayan-biswas0412 I have visited the website...I would suggest using some different color for the navbar and the footer. Otherwise, the website is awesome overall ❤
